// <auto-generated />
using System;
using Infrastructure.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009065404_seedData2")]
    partial class seedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "catgeory descriptopn L1",
                            IsDeleted = false,
                            Name = "Cat_1"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "catgeory descriptopn L2",
                            IsDeleted = false,
                            Name = "Cat_2"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Description U7FR3HVR7J9OGQK07JLU2YAL3L19BCR3M45UTTAB72HS4XIKHH",
                            IsDeleted = false,
                            Name = "Product1 WKQXV11R3F",
                            Price = 10m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Description ATUWLV1PR5CI3P8NP0FS33R2V2TUYNLGOJZU2SVFUWKG8ORA5G",
                            IsDeleted = false,
                            Name = "Product2 741MHT94LT",
                            Price = 20m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Description 6GX4QE8A2OYRF0OTLVXNOP33CM9T0UHD1K3WVKXBH7RXHMQ1EC",
                            IsDeleted = false,
                            Name = "Product3 TT9CBETDI0",
                            Price = 30m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Description 93E1KINFQOPPQUQL5DOHGL9H5HCL32WJFM9EWK654XU61TR144",
                            IsDeleted = false,
                            Name = "Product4 MEH1FLKETN",
                            Price = 40m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Description VCB046IXHL3HSEPD75352GQ1ASJLNU2CTAZ44NFNBG0HNLQLLB",
                            IsDeleted = false,
                            Name = "Product5 CV3P3YUSKK",
                            Price = 50m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Description 211KYSZXQ17PCQRQ3LLU0NV7P4CH9SXNQBD4R1S7XQYXCDTHYO",
                            IsDeleted = false,
                            Name = "Product6 0CTH6F4NGN",
                            Price = 60m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Description YM8EKLKZEYVWFHUGTJJCRYNOA7JKDBOH5YJXTAOGQEJPG0B06L",
                            IsDeleted = false,
                            Name = "Product7 MTVSV5QI8F",
                            Price = 70m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Description HVQHJNU859VGUXA6YSSD86WDPIFDO089BJMKIE7058TXTMZLH7",
                            IsDeleted = false,
                            Name = "Product8 426ZFJB3IU",
                            Price = 80m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Description PZ4R5HHM3ZXTKDTD9BIU8LIX22FL88V1E7SKO5QVIMJSNSKWXD",
                            IsDeleted = false,
                            Name = "Product9 D81X1E073D",
                            Price = 90m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Description DO6XQC9G830QQZ1H7I508BSOWB7LU3DG8WWAFLWCLCY58U7HX9",
                            IsDeleted = false,
                            Name = "Product10 FN2THGUTHF",
                            Price = 100m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Description 50Q94K37WRFEQMD0YGMTRR9HNAEH7N2A5528APK0K97C8BNRJF",
                            IsDeleted = false,
                            Name = "Product11 FNEKOAM3JC",
                            Price = 110m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Description 6S03IHOKA9IRTXDFUAMJE2OYW6XH6ACV45H2V662K4IY5TZ4L7",
                            IsDeleted = false,
                            Name = "Product12 CDR7RVDAFY",
                            Price = 120m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Description BUW174R2C7P7UB2JH91R3VQB8BUGS6WBBKB03J5PMLSJ2LLQ8G",
                            IsDeleted = false,
                            Name = "Product13 S39WMKD1D3",
                            Price = 130m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Description A7KC63D7J4OT6NG883SRDLP4P3U8NPSRZJV6QB671ERULU9NZQ",
                            IsDeleted = false,
                            Name = "Product14 PGSQDJR2N0",
                            Price = 140m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Description XF7RZAD5Y7VCQU9N9X8TJ4MV9BQELXFZ2PQL5I4YRJ09RCC17L",
                            IsDeleted = false,
                            Name = "Product15 B7PQ3YX889",
                            Price = 150m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Description CWCTKDBYWZ9PD6K13BTMWHASN3XBYFRXXQWMFWF1MV3P12UEX2",
                            IsDeleted = false,
                            Name = "Product16 6OQMTSXT7D",
                            Price = 160m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Description RWQRE3QCQGAS3NZQP5LPAIHV7BGYFFFPCTV42L5R6T2UY3DNK3",
                            IsDeleted = false,
                            Name = "Product17 OPVGVKH1LG",
                            Price = 170m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Description J50U2IRK4T3XIJXWVWKBY8478QQE5K9BR1RX55H4DSWR4WCGJX",
                            IsDeleted = false,
                            Name = "Product18 M4EAZIS6ZG",
                            Price = 180m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Description KOKH2ISGMQMB1WW3MBGR2LSZW5JK11296ORTW2ELXBDF1VA53C",
                            IsDeleted = false,
                            Name = "Product19 22J7OM1KWN",
                            Price = 190m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Description 6OI87AGPQL9KLLYZBROCYMLKNXV0GSFJIE9VXBKZO07YVND6H9",
                            IsDeleted = false,
                            Name = "Product20 VPRFSAY5DY",
                            Price = 200m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Description DUB6RB3OVX9YFFQC47A1BHD1UGFG320J205A2GZ4VHYNX4B2H9",
                            IsDeleted = false,
                            Name = "Product21 H58Y1CA8LF",
                            Price = 210m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Description VRRANSLOC8A59PBXAE7QJ3X76D385SKWYN1WCZTA9JUTNG34AX",
                            IsDeleted = false,
                            Name = "Product22 3Q2CRHQHNO",
                            Price = 220m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Description AVYL18ESOE4D750MWHCI16T9SQ968ARK1YR8SWDSMJNS2F2IK3",
                            IsDeleted = false,
                            Name = "Product23 DHAZIO044J",
                            Price = 230m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Description PQ2C3OOI0A1RS3WYLBMAZIS21C0P91ORS6Z6TUN53P370INAKX",
                            IsDeleted = false,
                            Name = "Product24 05E9ZIRFCJ",
                            Price = 240m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Description 1RNH9SCYCCGJSER48A8207JAQ1BA4JN67Y9ZETO7AAJOLNKSW1",
                            IsDeleted = false,
                            Name = "Product25 73TT3CD1ZL",
                            Price = 250m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Description ZE8OFGDIPVMOULUED430YKVVIRZFSPP2YSS3ACHRYVAKU2U8AZ",
                            IsDeleted = false,
                            Name = "Product26 TFDLP9C4E6",
                            Price = 260m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Description = "Description 3X4YWZ8PEOPI2UQ0J3HJSDDDS9ULTR39KIW33XR52FI7R9Z8QS",
                            IsDeleted = false,
                            Name = "Product27 P8RTEM18HP",
                            Price = 270m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Description 21LV8EFVK72LA2RZC7Q1GNJGKKRWDGKH8M6U7WHPKSG5Q1B0CW",
                            IsDeleted = false,
                            Name = "Product28 33MVZFZWYJ",
                            Price = 280m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "Description NGJGJVY2KU09FJFH5R3NH3EB1SC7EQRZHKPHIP7ND7YTM1PNZZ",
                            IsDeleted = false,
                            Name = "Product29 C1PHPY4DK5",
                            Price = 290m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Description FHRL2PZ8H12VM80S5COE2ESFV8FP97Q6F01T6SJV1M3WEBS7FQ",
                            IsDeleted = false,
                            Name = "Product30 0XGZPQ93DN",
                            Price = 300m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "Description MSDXPSQO4K5DE8ZDD1OBRMZ1I7SWCYBR13E887LMK745CXSS5Z",
                            IsDeleted = false,
                            Name = "Product31 RM1W1AROKN",
                            Price = 310m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Description VGHUW14IAKFXKK4XV4TZZNO7C1S4COK4CQB8JD3NFOI36P04SW",
                            IsDeleted = false,
                            Name = "Product32 G0MRXFTNRC",
                            Price = 320m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Description = "Description C9DJCVO74G3AIDJU8SRVSV9GI3297GL96N7YQ8G5Y1BBA5FH17",
                            IsDeleted = false,
                            Name = "Product33 CX6BHAOEK7",
                            Price = 330m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Description 1VN81V85SEW2POBEK84SKM7ENNI2WMN15FNK4I2MEPBIS5EBL6",
                            IsDeleted = false,
                            Name = "Product34 6LKAFHEWCN",
                            Price = 340m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Description AMUEB3PQLU2VDJQLWG8FU3UU42GBB1Y16XAKDC91L0DPFSZWXH",
                            IsDeleted = false,
                            Name = "Product35 16F4ZFJHJP",
                            Price = 350m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Description = "Description Y6QC4QHS68B0RUBK1W6SQFSCLQGNR6DXUM73HTO8KWPL9UPWRA",
                            IsDeleted = false,
                            Name = "Product36 LLIYT43KLL",
                            Price = 360m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            Description = "Description N6CL3O437K3ZZXQN0RKZ1P7XORPKLIDZZY9JEVR5BOR9YDOF3J",
                            IsDeleted = false,
                            Name = "Product37 7IRMPMJ1J2",
                            Price = 370m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Description 6YI3GPQJ81IUJWRAH3BP2ZJGFSJ2B3WBL860GUGSWJ0OGOO37K",
                            IsDeleted = false,
                            Name = "Product38 FNOBHBFX4J",
                            Price = 380m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            Description = "Description DKSUAZ0MAXL5DES06KBJN9YM1G3NZS0MGO3YCO33KETPXMRKRC",
                            IsDeleted = false,
                            Name = "Product39 W2J5BMSZ21",
                            Price = 390m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "Description 8AT0BDXQTXTIZJJDEMNSL0207UYTCOXPQ5TQXLRIMXYLR7687F",
                            IsDeleted = false,
                            Name = "Product40 1IO6QUC46L",
                            Price = 400m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Description = "Description X854PRH7P07LDSN1M3K8YY4IDMHDGLED83O7ITZ3XMMJW6TT8N",
                            IsDeleted = false,
                            Name = "Product41 6VQ631DLKV",
                            Price = 410m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            Description = "Description LFK1DRTKBOWR6HZQ9ONWE7RULJZAYNR2EWMOHZ4QXEPWWT2YOX",
                            IsDeleted = false,
                            Name = "Product42 9WL23SR0AJ",
                            Price = 420m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            Description = "Description TK32OQROU75NVV2E9VMWOY2N2Z974ZC7P7XS2SEY0A60KXXNAF",
                            IsDeleted = false,
                            Name = "Product43 82J5VQICMF",
                            Price = 430m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Description = "Description VXR6CVNTVVX6R9BFLVYI9EEQD3CUHXFJIFD3HYZSZAH3DCCFD4",
                            IsDeleted = false,
                            Name = "Product44 OB7A07T414",
                            Price = 440m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            Description = "Description OKCSUACMG9MIGK25060MSXR7VB64J5E0SD7XPYFCJA3S894PRG",
                            IsDeleted = false,
                            Name = "Product45 ZJB3HSAVS3",
                            Price = 450m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            Description = "Description 76SFRI2EAI0DDHISQGKP36RAHEWH57BP3TRYSCEOZCYIA6J5AM",
                            IsDeleted = false,
                            Name = "Product46 SH4EJ30LKN",
                            Price = 460m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            Description = "Description CRBRE0UPR4EVSUF93XWF64H23D4OF7R0XYTOOW67NUV0WDELHV",
                            IsDeleted = false,
                            Name = "Product47 US5PAMXGPD",
                            Price = 470m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            Description = "Description SMB9OEOGLKYDW9PLJEDBY477TRC4RMZ1L8POP35TE3347WSG7R",
                            IsDeleted = false,
                            Name = "Product48 QU3L6YM8VX",
                            Price = 480m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            Description = "Description AMRQIGS5E4FF86IQEDZWF9PW7K8V1DAY0FDK5MLQYH5HV2Y0UG",
                            IsDeleted = false,
                            Name = "Product49 HMBU805RDI",
                            Price = 490m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            Description = "Description 30EDCVDI6YHTBNBF87BN9LO9SC82Z2XS0S9OK2TEW1JAQWVWS5",
                            IsDeleted = false,
                            Name = "Product50 UGH3ST7FMR",
                            Price = 500m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            Description = "Description RECHRL3BW5RASDCELNZBNIUW4RTPO5TM9BXZXTE8YM904LC1TO",
                            IsDeleted = false,
                            Name = "Product51 TWVEJXYHHK",
                            Price = 510m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 2,
                            Description = "Description LQUY0I6WOZDYYJ540TI18V4HPAT4G61HJCFBU5KN7UZVZJ7DO8",
                            IsDeleted = false,
                            Name = "Product52 WR5LO86VFQ",
                            Price = 520m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            Description = "Description 4N1FET8NAWEOSZQTFBD40RIMI49NQYBH3SZQX1HF8TV2AYVPOI",
                            IsDeleted = false,
                            Name = "Product53 8EDG4DKNW1",
                            Price = 530m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            Description = "Description E09BWDJGPEZ2G0HWCYCRHEEK90KFALD94DK1GFLD17U15CPRO1",
                            IsDeleted = false,
                            Name = "Product54 TFS7TP5CPX",
                            Price = 540m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 2,
                            Description = "Description MIYPMZ78MWZUDMDANKN696BPIGQ2COXACE0A2HW8LRA0HFFCTR",
                            IsDeleted = false,
                            Name = "Product55 3UKWAZXUC3",
                            Price = 550m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            Description = "Description L2UIKNKZ2UXG5LG1WMYT8LC73HCPQZZIGMFT0CRA3X337SRNF6",
                            IsDeleted = false,
                            Name = "Product56 SHCAQOVGSQ",
                            Price = 560m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 2,
                            Description = "Description YFQ8PXDJJSTLTNRDMRX7PS58RKQRWDCS7Y3L97D3VKV5REO3U8",
                            IsDeleted = false,
                            Name = "Product57 MPNI0QPRNT",
                            Price = 570m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 2,
                            Description = "Description 7W9114PO2408IZMPOUYAAXWD0KCM0UEQI1W4PZYD3RSNO6F9SH",
                            IsDeleted = false,
                            Name = "Product58 7TKL0FVWYC",
                            Price = 580m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            Description = "Description Y994BJTVRZTH1RB4V9V6DED6BWEH602O22BAGD74TPEIH2RMAP",
                            IsDeleted = false,
                            Name = "Product59 233NGWCSXG",
                            Price = 590m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 2,
                            Description = "Description 1PXICLY7BP6WI57BUAPD8Z3F4645NW65B9O4PRD73NS2Z5309I",
                            IsDeleted = false,
                            Name = "Product60 4QXLB7EATW",
                            Price = 600m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            Description = "Description AKRHO218CN48P51WJ6JRAYQB106A74M3APMWSBXEV1BTMVNPWY",
                            IsDeleted = false,
                            Name = "Product61 AQRUI3PVVF",
                            Price = 610m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 2,
                            Description = "Description HWS2KQBW9A3J902G87W3U47V3S8JTH4VPTCHH32KUEMUG45ZI9",
                            IsDeleted = false,
                            Name = "Product62 V9H8N8XV6M",
                            Price = 620m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 2,
                            Description = "Description HTRDDMJMV9GZ2V3KK6C4SYOKWBW56B75AR5NY8CJ9LLFPGQQSP",
                            IsDeleted = false,
                            Name = "Product63 N33C2R19K2",
                            Price = 630m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 2,
                            Description = "Description UH71WGJCBV3N6X9ST4J6WG469BJCUJ4DQN68XKFV40WSSRPDMD",
                            IsDeleted = false,
                            Name = "Product64 JPQCD75RXC",
                            Price = 640m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            Description = "Description J02EM700OUT0286FSH3R7ZGHY4QALVUL5KDV4HNTCSQ54T3WIK",
                            IsDeleted = false,
                            Name = "Product65 TK6Y4J8HS9",
                            Price = 650m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            Description = "Description 0SABTIGQETDAZTEEUETER6EYTG5158Z1LDJ7YB69X11FZRY21H",
                            IsDeleted = false,
                            Name = "Product66 O7RTAAZHRV",
                            Price = 660m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 2,
                            Description = "Description OAWWH0MVVW8UHM6UH4M93UU7M4DNGYHVCUS66D6ZDG7JEQTBNB",
                            IsDeleted = false,
                            Name = "Product67 RTNULU5Y6B",
                            Price = 670m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            Description = "Description 3XWWZ2EETHB2XMIJCPL5AQMSZ2582E63LH4ZZUG7XZ4AJSGZNO",
                            IsDeleted = false,
                            Name = "Product68 VI4QTEDBQ8",
                            Price = 680m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            Description = "Description MDW9PX9ZQUONUMU418SD2SN83AVPW0FYABZC0K3OCV59CA4EJ2",
                            IsDeleted = false,
                            Name = "Product69 9C54NISD4Y",
                            Price = 690m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            Description = "Description BJBS2HEF68U6Z0A0GQPJXCFSZID1OSKZUD1W38YGJG6WGTWD02",
                            IsDeleted = false,
                            Name = "Product70 PL90K6Y0TR",
                            Price = 700m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            Description = "Description 51HL38J6Z7NP6MYEZ6TZRJ0T2795LQW2BI9P44X1E7RSY09W5H",
                            IsDeleted = false,
                            Name = "Product71 HQJGOWTY15",
                            Price = 710m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 2,
                            Description = "Description AC11HUJEZ677T0POMK3M7GIB0U2KPEPFXE5M95C5PJUQC86UV1",
                            IsDeleted = false,
                            Name = "Product72 M8C2X5PTC4",
                            Price = 720m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 2,
                            Description = "Description C4ZKK82RI5BIR22C60PKSHGOPB75R01CGRFG5OMJI3AR2RA56G",
                            IsDeleted = false,
                            Name = "Product73 OY3U89T9RA",
                            Price = 730m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 2,
                            Description = "Description QL0J825RYV20YLGALQISR3C9JVOC69X72TGL2DNHCGO4E1XFH2",
                            IsDeleted = false,
                            Name = "Product74 EQPN4T6KWG",
                            Price = 740m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 2,
                            Description = "Description JRKN6J72GWY2LNS2G918K6IM2CWPTZZNT30V62HJ7D5WBEHJYJ",
                            IsDeleted = false,
                            Name = "Product75 WVQBY9GHG3",
                            Price = 750m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 2,
                            Description = "Description 5Y0RODPDNG6P1GSOO4STLJUIH5XW7HQEW01AIP6OUGQQ2OH3RJ",
                            IsDeleted = false,
                            Name = "Product76 4C1SW8BI91",
                            Price = 760m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 2,
                            Description = "Description 3PRU9Y3M37YCZOAU5PT1O1XETEK38BX5QDYT97DUXKY7Q95V6B",
                            IsDeleted = false,
                            Name = "Product77 F83IAY17OV",
                            Price = 770m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 2,
                            Description = "Description LGC482GXJLNOVIBWMTNFCQZ3PWZDDWDI3R8RPV1QK95QJU7IG2",
                            IsDeleted = false,
                            Name = "Product78 PQ36418R4F",
                            Price = 780m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 2,
                            Description = "Description XEFDCKPSI40K5TGGRLGL8QEDID7WEL7W7WADVHDJPG61ZRDZVJ",
                            IsDeleted = false,
                            Name = "Product79 SJ7GX14E8U",
                            Price = 790m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 2,
                            Description = "Description FRF4I16NI92GR69FQHK9BB4YHNRMD14E4EBXKQ6TY4MTYQI2IL",
                            IsDeleted = false,
                            Name = "Product80 T8CVUE0UGV",
                            Price = 800m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            Description = "Description LCHCTDHKW5363IU8N8Y6FE7FGFQ4YZJTH04Y1Y1CEMT5PO4QPP",
                            IsDeleted = false,
                            Name = "Product81 REL6PZDQOT",
                            Price = 810m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 2,
                            Description = "Description 3PFJSU53D3E5OBE0C3B9XZ5UGCUD2RI9CHLOQPPMKMETZX9S89",
                            IsDeleted = false,
                            Name = "Product82 9ODUA9JFB6",
                            Price = 820m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            Description = "Description PXHBDAHSIZOU2MTX9FMC1WIGAOF32PXL01RARVO5NJB0A1DLM9",
                            IsDeleted = false,
                            Name = "Product83 KYP36S50PH",
                            Price = 830m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 2,
                            Description = "Description O04DN7RYDYYONIOG4V11XM8OGGIEF53VIGOT1513KFG59PUXHU",
                            IsDeleted = false,
                            Name = "Product84 28R0HKF7VJ",
                            Price = 840m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 2,
                            Description = "Description ASFKRRY6XRK23DWEQEBVKFVQ4AZ3HKBMP4TKNHPPEZVSJQFQ3Q",
                            IsDeleted = false,
                            Name = "Product85 AKR24OATQW",
                            Price = 850m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 2,
                            Description = "Description VW7FZX3LU0545QILQ2VDVKQH4U8UL4WPRZCRASXWACXSKG5KDH",
                            IsDeleted = false,
                            Name = "Product86 U099LI6CL9",
                            Price = 860m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 2,
                            Description = "Description 84EN7HDIWTJR8YAZHP2RF0A17ZXNDKNF9W4RLN7G43S6MPIWNK",
                            IsDeleted = false,
                            Name = "Product87 BDHJGCZKBQ",
                            Price = 870m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 2,
                            Description = "Description U6CBS77TERH1NIL8I5N37UYL3HP1DSR733JGPIZVI42KXZ7UN1",
                            IsDeleted = false,
                            Name = "Product88 PMJH95XK6V",
                            Price = 880m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 2,
                            Description = "Description Y1FDZWN5NTNTGPRK2TW1OISIC4DMUWYVYTN7B8VFYH38O2EHDH",
                            IsDeleted = false,
                            Name = "Product89 UYCGSLIWPY",
                            Price = 890m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 2,
                            Description = "Description 2F5V9FR6Q6VJH97PT1C5XN5Q3TASUA4N5L495L6A4QZ3LC0RN8",
                            IsDeleted = false,
                            Name = "Product90 1UHUJ47L8I",
                            Price = 900m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            Description = "Description IMI46ONE5G4FHJQ12IJLNMZCD1WVKIH0MTDN24SUKNHA01PBSB",
                            IsDeleted = false,
                            Name = "Product91 ZRZFPTKI76",
                            Price = 910m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 2,
                            Description = "Description L91A6HMRMNI8TRWXQ2GNMCRG10JHG6X0HXMJ1NG6FGTHJNZHR7",
                            IsDeleted = false,
                            Name = "Product92 91C6N5PUYA",
                            Price = 920m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 2,
                            Description = "Description ZLXCIQMLIROESDP051UX2XNED008Q8GVNCJUBA7UJPCYLXE4RK",
                            IsDeleted = false,
                            Name = "Product93 Y5EMFK82RK",
                            Price = 930m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 2,
                            Description = "Description GBIY30PLJBK3FBA50ADW0UVJLDVZSJ7SCNG1DQQ8R22W0DTK52",
                            IsDeleted = false,
                            Name = "Product94 5FSTXNCMON",
                            Price = 940m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 2,
                            Description = "Description H7BLN865MZAOR90DI8H5MV3BORYIEAUTXCPOKI4VB36V5438PW",
                            IsDeleted = false,
                            Name = "Product95 GF4CFAQSSA",
                            Price = 950m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 2,
                            Description = "Description KKTDOQBRG25RG81DP4FJ9Z4YZHQCBZPRW4F4KZJVY93BO165S0",
                            IsDeleted = false,
                            Name = "Product96 KXMERU02FP",
                            Price = 960m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 2,
                            Description = "Description 0G0C3UL5SUXSE4RAM3UQ0A8ZP7UHKYYTI39RAMHERP5BFXKPGD",
                            IsDeleted = false,
                            Name = "Product97 23P0N29CBR",
                            Price = 970m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 2,
                            Description = "Description E34F0ZIT6SF19JI5U6BFBZU5WRD9WFGA6Z4AIGMIFKLS484X4K",
                            IsDeleted = false,
                            Name = "Product98 VHG1GEQQ1F",
                            Price = 980m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 2,
                            Description = "Description HRPJ0JLUFCV0H9702BCQM66SQM3WPK6QK1XS79I0D6DJGRCGT0",
                            IsDeleted = false,
                            Name = "Product99 D2R4IP2EYJ",
                            Price = 990m,
                            UserId = "951d5cf7-c470-4504-ba7e-31bd07e43589"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "df7900ec-a99a-453a-84d0-a296bd5614c6",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "aec66ad6-82e6-4b85-a19d-483f3b202439",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "e9325ad8-cd6e-4751-90a4-d168bdff082d",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
